// Example: Using React in Artisan with Module System
// React is pre-vendored, so we can use it directly

import { require, registerModule } from "art/modules";

export function setupReactApplication(): void {
  console.log("Setting up React application...");

  // React is already available (pre-vendored)
  const React = require("react");
  const ReactDOM = require("react-dom");

  console.log("✓ React loaded");
  console.log("✓ React version:", React.version || "18.3.1");

  // Register additional React packages if bundled
  registerAdditionalReactPackages();

  // Initialize the app
  initializeApp();
}

// ============================================================================
// Setup Pre-vendored React
// ============================================================================

function initializeApp(): void {
  const React = require("react");
  const { useState, useEffect } = React;

  // Define a simple functional component
  function Counter() {
    const [count, setCount] = useState(0);

    return React.createElement(
      "div",
      { className: "counter" },
      React.createElement("p", null, `Count: ${count}`),
      React.createElement(
        "button",
        { onClick: () => setCount(count + 1) },
        "Increment"
      ),
      React.createElement(
        "button",
        { onClick: () => setCount(0) },
        "Reset"
      )
    );
  }

  console.log("✓ Counter component created");

  // Example: Class component with lifecycle
  class DataComponent {
    state: any = { data: null, loading: true };

    componentDidMount() {
      // Simulate async data loading
      setTimeout(() => {
        this.state.data = ["Item 1", "Item 2", "Item 3"];
        this.state.loading = false;
      }, 1000);
    }

    render() {
      if (this.state.loading) {
        return React.createElement("div", null, "Loading...");
      }
      return React.createElement(
        "ul",
        null,
        this.state.data.map((item: string) =>
          React.createElement("li", { key: item }, item)
        )
      );
    }
  }

  console.log("✓ DataComponent created");

  // Example: Hooks usage
  demonstrateHooks();
}

function demonstrateHooks(): void {
  const React = require("react");
  const { useState, useEffect, useCallback, useMemo, useRef } = React;

  console.log("\n=== React Hooks Demo ===");

  // useState
  function StateExample() {
    const [count, setCount] = useState(0);
    const [name, setName] = useState("React");

    return {
      count,
      setCount,
      name,
      setName
    };
  }

  const stateDemo = StateExample();
  console.log("✓ useState hook available");
  console.log("  - count:", stateDemo.count);
  console.log("  - name:", stateDemo.name);

  // useCallback
  function CallbackExample() {
    const [count, setCount] = useState(0);

    const increment = useCallback(() => {
      setCount((c: number) => c + 1);
    }, []);

    return { count, increment };
  }

  console.log("✓ useCallback hook available");

  // useMemo
  function MemoExample() {
    const [count, setCount] = useState(0);

    const doubled = useMemo(() => {
      console.log("Computing doubled...");
      return count * 2;
    }, [count]);

    return { count, doubled };
  }

  console.log("✓ useMemo hook available");

  // useRef
  function RefExample() {
    const inputRef = useRef(null);

    const focus = () => {
      if (inputRef.current) {
        // Would focus input in real React app
      }
    };

    return { inputRef, focus };
  }

  console.log("✓ useRef hook available");
}

// ============================================================================
// Register Additional React Packages (if bundled)
// ============================================================================

function registerAdditionalReactPackages(): void {
  // Example: Register React Router if bundled
  // This would come from a bundle generated by esbuild

  registerModule("react-router-dom", function(module, exports, require) {
    // React Router would be bundled here
    // For now, we provide a minimal implementation

    const React = require("react");

    // BrowserRouter component
    exports.BrowserRouter = React.memo(({ children }: any) => {
      return React.createElement("div", { className: "router" }, children);
    });

    // Routes component
    exports.Routes = React.memo(({ children }: any) => {
      return React.createElement("div", { className: "routes" }, children);
    });

    // Route component
    exports.Route = ({ path, element }: any) => element;

    // Link component
    exports.Link = ({ to, children }: any) => {
      return React.createElement(
        "a",
        { href: to, className: "link" },
        children
      );
    };

    // useNavigate hook
    exports.useNavigate = () => {
      return (path: string) => {
        window.location.href = path;
      };
    };
  });

  // Example: Register state management (Redux-like)
  registerModule("react-redux", function(module, exports, require) {
    const React = require("react");

    // Provider component
    exports.Provider = ({ store, children }: any) => {
      return React.createElement("div", { className: "provider" }, children);
    };

    // useSelector hook
    exports.useSelector = (selector: any) => {
      return selector({});
    };

    // useDispatch hook
    exports.useDispatch = () => {
      return (action: any) => {
        console.log("Action dispatched:", action);
      };
    };
  });
}

// ============================================================================
// Complete Example: Todo App Component
// ============================================================================

export function createTodoApp(): void {
  console.log("\n=== Todo App Example ===");

  const React = require("react");
  const { useState, useEffect } = React;

  function TodoApp() {
    const [todos, setTodos] = useState([
      { id: 1, text: "Learn React", done: false },
      { id: 2, text: "Build app", done: false },
      { id: 3, text: "Deploy", done: false }
    ]);

    const [newTodo, setNewTodo] = useState("");

    const addTodo = () => {
      if (newTodo.trim()) {
        setTodos([
          ...todos,
          { id: Date.now(), text: newTodo, done: false }
        ]);
        setNewTodo("");
      }
    };

    const toggleTodo = (id: number) => {
      setTodos(todos.map(todo =>
        todo.id === id ? { ...todo, done: !todo.done } : todo
      ));
    };

    const removeTodo = (id: number) => {
      setTodos(todos.filter(todo => todo.id !== id));
    };

    return {
      todos,
      newTodo,
      setNewTodo,
      addTodo,
      toggleTodo,
      removeTodo
    };
  }

  const app = TodoApp();
  console.log("✓ Todo app created");
  console.log("  - Todos:", app.todos.length);
  console.log("  - Can add, toggle, remove todos");
}

// ============================================================================
// Bundling Example: How to use bundled packages
// ============================================================================

export function exampleBundledPackageUsage(): void {
  console.log("\n=== Bundled Package Usage Example ===");

  // If you have bundled React Router:
  const canUseRouter = (() => {
    try {
      const Router = require("react-router-dom");
      return typeof Router.BrowserRouter === "function";
    } catch {
      return false;
    }
  })();

  if (canUseRouter) {
    console.log("✓ React Router available");

    const Router = require("react-router-dom");

    // Example router setup
    function AppWithRouter() {
      const React = require("react");

      return React.createElement(
        Router.BrowserRouter,
        null,
        React.createElement(
          Router.Routes,
          null,
          React.createElement(Router.Route, {
            path: "/",
            element: React.createElement("h1", null, "Home")
          })
        )
      );
    }

    console.log("✓ Router app component created");
  } else {
    console.log("ℹ React Router not bundled (optional)");
  }
}

// ============================================================================
// Advanced: React Context for Global State
// ============================================================================

export function demonstrateContextAPI(): void {
  console.log("\n=== React Context API ===");

  const React = require("react");
  const { createContext, useContext, useState } = React;

  // Create a context
  const AppContext = createContext({});

  // Provider component
  function AppProvider({ children }: any) {
    const [user, setUser] = useState({
      name: "John Doe",
      email: "john@example.com",
      role: "admin"
    });

    const value = { user, setUser };

    return React.createElement(
      AppContext.Provider,
      { value },
      children
    );
  }

  // Consumer hook
  function useAppContext() {
    return useContext(AppContext);
  }

  // Example component that uses context
  function UserProfile() {
    const context = useAppContext();

    return React.createElement(
      "div",
      { className: "profile" },
      React.createElement("h1", null, context?.user?.name || "User"),
      React.createElement("p", null, context?.user?.email || "N/A")
    );
  }

  console.log("✓ Context API demonstrated");
  console.log("✓ AppProvider created");
  console.log("✓ useAppContext hook available");
  console.log("✓ UserProfile component created");
}

// ============================================================================
// Entry point for Artisan integration
// ============================================================================

/*

To use this in your Artisan application:

import { setupReactApplication, createTodoApp, demonstrateContextAPI } from "./app.ts";

export function onApplicationStart(): void {
  // Initialize React and register bundled packages
  setupReactApplication();

  // Create example todo app
  createTodoApp();

  // Show Context API example
  demonstrateContextAPI();

  // Your app is now ready to use React!
}

*/
