// embed_text - a tiny, generic build-time tool: reads a text file and
// emits a .cpp defining a zero-argument C function that returns its
// contents as a string. Used by CMakeLists.txt (and artisan-cli, which
// just drives the same CMake build) to bake an optional .js file straight
// into the binary, the same way artisanc embeds markup and <img> bytes -
// nothing about this tool is JS-specific, it just turns text into data.

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

namespace {

std::string EscapeStringLiteral(const std::string &text) {
  std::string out;
  out.reserve(text.size());

  for (char c : text) {
    switch (c) {
    case '"':
      out += "\\\"";
      break;
    case '\\':
      out += "\\\\";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\t':
      out += "\\t";
      break;
    case '\r':
      break;
    default:
      out += c;
    }
  }

  return out;
}

std::string ReadFile(const std::string &path) {
  std::ifstream file(path);
  if (!file) {
    std::cerr << "embed_text: failed to open " << path << "\n";
    std::exit(1);
  }

  std::ostringstream contents;
  contents << file.rdbuf();
  return contents.str();
}

} // namespace

int main(int argc, char *argv[]) {
  if (argc != 4) {
    std::cerr << "usage: embed_text <input_text_file> <output.cpp> "
                 "<function_name>\n";
    return 1;
  }

  const std::string inputPath = argv[1];
  const std::string outputPath = argv[2];
  const std::string functionName = argv[3];

  std::string text = ReadFile(inputPath);

  std::ofstream out(outputPath);
  if (!out) {
    std::cerr << "embed_text: failed to open " << outputPath
               << " for writing\n";
    return 1;
  }

  out << "// Generated by embed_text from " << inputPath << " - do not edit.\n\n";
  out << "namespace artisan {\n\n";
  out << "const char *" << functionName << "() {\n";
  out << "  static const char kText[] = \"" << EscapeStringLiteral(text)
      << "\";\n";
  out << "  return kText;\n";
  out << "}\n\n";
  out << "} // namespace artisan\n";

  return 0;
}
